# Tasas de plazo fijo — Argentina

El BCRA publica diariamente el promedio ponderado de la tasa
del plazo fijo a 30 días. Es un benchmark de mercado, sin tratarse de un promedio simple, sino ponderado por volumen.

In [1]:
import requests
import pandas as pd
import sqlite3 
from datetime import date

url = "https://api.bcra.gob.ar/estadisticas/v4.0/Monetarias/12"

response = requests.get(url, timeout=10)
response.raise_for_status()
data_monetaria = response.json()

In [2]:
print(response.status_code) #verifico que la API sea la correcta

200

In [3]:
print(data_monetaria.keys())

dict_keys(['status', 'metadata', 'results'])

In [4]:
print(data_monetaria["results"])

[{'idVariable': 12, 'detalle': [{'fecha': '2026-03-27', 'valor': 23.9}, {'fecha': '2026-03-26', 'valor': 25.1}, {'fecha': '2026-03-25', 'valor': 24.88}, {'fecha': '2026-03-20', 'valor': 24.97}, {'fecha': '2026-03-19', 'valor': 25.95}, {'fecha': '2026-03-18', 'valor': 26.31}, {'fecha': '2026-03-17', 'valor': 27.18}, {'fecha': '2026-03-16', 'valor': 27.39}, {'fecha': '2026-03-13', 'valor': 27.16}, {'fecha': '2026-03-12', 'valor': 27.81}, {'fecha': '2026-03-11', 'valor': 27.28}, {'fecha': '2026-03-10', 'valor': 28.27}, {'fecha': '2026-03-09', 'valor': 27.66}, {'fecha': '2026-03-06', 'valor': 27.5}, {'fecha': '2026-03-05', 'valor': 27.27}, {'fecha': '2026-03-04', 'valor': 27.37}, {'fecha': '2026-03-03', 'valor': 27.88}, {'fecha': '2026-03-02', 'valor': 28.08}, {'fecha': '2026-02-27', 'valor': 28.28}, {'fecha': '2026-02-26', 'valor': 29.12}, {'fecha': '2026-02-25', 'valor': 28.04}, {'fecha': '2026-02-24', 'valor': 31.82}, {'fecha': '2026-02-23', 'valor': 30.16}, {'fecha': '2026-02-20', 'valor': 30.75}, {'fecha': '2026-02-19', 'valor': 30.34}, {'fecha': '2026-02-18', 'valor': 28.91}, {'fecha': '2026-02-13', 'valor': 28.18}, {'fecha': '2026-02-12', 'valor': 28.04}, {'fecha': '2026-02-11', 'valor': 27.11}, {'fecha': '2026-02-10', 'valor': 28.63}, {'fecha': '2026-02-09', 'valor': 27.86}, {'fecha': '2026-02-06', 'valor': 28.52}, {'fecha': '2026-02-05', 'valor': 29.14}, {'fecha': '2026-02-04', 'valor': 28.51}, {'fecha': '2026-02-03', 'valor': 30.13}, {'fecha': '2026-02-02', 'valor': 28.21}, {'fecha': '2026-01-30', 'valor': 28.57}, {'fecha': '2026-01-29', 'valor': 28.62}, {'fecha': '2026-01-28', 'valor': 29.29}, {'fecha': '2026-01-27', 'valor': 31.28}, {'fecha': '2026-01-26', 'valor': 29.29}, {'fecha': '2026-01-23', 'valor': 33.06}, {'fecha': '2026-01-22', 'valor': 32.93}, {'fecha': '2026-01-21', 'valor': 30.67}, {'fecha': '2026-01-20', 'valor': 30.87}, {'fecha': '2026-01-19', 'valor': 30.02}, {'fecha': '2026-01-16', 'valor': 29.93}, {'fecha': '2026-01-15', 'valor': 29.88}, {'fecha': '2026-01-14', 'valor': 28.78}, {'fecha': '2026-01-13', 'valor': 28.56}, {'fecha': '2026-01-12', 'valor': 25.86}, {'fecha': '2026-01-09', 'valor': 26.37}, {'fecha': '2026-01-08', 'valor': 27.55}, {'fecha': '2026-01-07', 'valor': 28.43}, {'fecha': '2026-01-06', 'valor': 26.64}, {'fecha': '2026-01-05', 'valor': 25.64}, {'fecha': '2026-01-02', 'valor': 25.22}, {'fecha': '2025-12-30', 'valor': 25.46}, {'fecha': '2025-12-29', 'valor': 25.29}, {'fecha': '2025-12-26', 'valor': 25.38}, {'fecha': '2025-12-23', 'valor': 27.44}, {'fecha': '2025-12-22', 'valor': 26.04}, {'fecha': '2025-12-19', 'valor': 25.63}, {'fecha': '2025-12-18', 'valor': 25.12}, {'fecha': '2025-12-17', 'valor': 25.0}, {'fecha': '2025-12-16', 'valor': 24.92}, {'fecha': '2025-12-15', 'valor': 24.8}, {'fecha': '2025-12-12', 'valor': 24.24}, {'fecha': '2025-12-11', 'valor': 24.52}, {'fecha': '2025-12-10', 'valor': 24.73}, {'fecha': '2025-12-09', 'valor': 24.93}, {'fecha': '2025-12-05', 'valor': 25.56}, {'fecha': '2025-12-04', 'valor': 25.68}, {'fecha': '2025-12-03', 'valor': 26.47}, {'fecha': '2025-12-02', 'valor': 28.41}, {'fecha': '2025-12-01', 'valor': 28.06}, {'fecha': '2025-11-28', 'valor': 29.03}, {'fecha': '2025-11-27', 'valor': 29.06}, {'fecha': '2025-11-26', 'valor': 28.91}, {'fecha': '2025-11-25', 'valor': 29.32}, {'fecha': '2025-11-20', 'valor': 30.62}, {'fecha': '2025-11-19', 'valor': 31.19}, {'fecha': '2025-11-18', 'valor': 30.55}, {'fecha': '2025-11-17', 'valor': 30.27}, {'fecha': '2025-11-14', 'valor': 30.7}, {'fecha': '2025-11-13', 'valor': 30.97}, {'fecha': '2025-11-12', 'valor': 30.88}, {'fecha': '2025-11-11', 'valor': 32.73}, {'fecha': '2025-11-10', 'valor': 32.01}, {'fecha': '2025-11-07', 'valor': 33.05}, {'fecha': '2025-11-05', 'valor': 34.17}, {'fecha': '2025-11-04', 'valor': 35.94}, {'fecha': '2025-11-03', 'valor': 35.06}, {'fecha': '2025-10-31', 'valor': 37.49}, {'fecha': '2025-10-30', 'valor': 39.32}, {'fecha': '2025-10-29', 'valor': 40.91}, {'fecha': '2025-10-28', 'valor': 44.82}, {'fecha': '2025-10-27', 'valor': 43.3}, {'fecha': '2025-10-24', 'valor': 47.12}, {'fecha': '2025-10-23', 'valor': 47.06}, {'fecha': '2025-10-22', 'valor': 47.09}, {'fecha': '2025-10-21', 'valor': 48.77}, {'fecha': '2025-10-20', 'valor': 48.28}, {'fecha': '2025-10-17', 'valor': 49.45}, {'fecha': '2025-10-16', 'valor': 54.44}, {'fecha': '2025-10-15', 'valor': 51.47}, {'fecha': '2025-10-14', 'valor': 49.38}, {'fecha': '2025-10-13', 'valor': 45.44}, {'fecha': '2025-10-09', 'valor': 46.08}, {'fecha': '2025-10-08', 'valor': 41.85}, {'fecha': '2025-10-07', 'valor': 42.3}, {'fecha': '2025-10-06', 'valor': 39.98}, {'fecha': '2025-10-03', 'valor': 39.49}, {'fecha': '2025-10-02', 'valor': 39.93}, {'fecha': '2025-10-01', 'valor': 40.17}, {'fecha': '2025-09-30', 'valor': 37.67}, {'fecha': '2025-09-29', 'valor': 38.8}, {'fecha': '2025-09-26', 'valor': 37.78}, {'fecha': '2025-09-25', 'valor': 39.22}, {'fecha': '2025-09-24', 'valor': 43.22}, {'fecha': '2025-09-23', 'valor': 45.64}, {'fecha': '2025-09-22', 'valor': 43.72}, {'fecha': '2025-09-19', 'valor': 43.78}, {'fecha': '2025-09-18', 'valor': 43.89}, {'fecha': '2025-09-17', 'valor': 43.03}, {'fecha': '2025-09-16', 'valor': 43.34}, {'fecha': '2025-09-15', 'valor': 44.71}, {'fecha': '2025-09-12', 'valor': 45.42}, {'fecha': '2025-09-11', 'valor': 49.43}, {'fecha': '2025-09-10', 'valor': 51.16}, {'fecha': '2025-09-09', 'valor': 55.64}, {'fecha': '2025-09-08', 'valor': 53.62}, {'fecha': '2025-09-05', 'valor': 52.72}, {'fecha': '2025-09-04', 'valor': 56.06}, {'fecha': '2025-09-03', 'valor': 52.49}, {'fecha': '2025-09-02', 'valor': 53.62}, {'fecha': '2025-09-01', 'valor': 54.57}, {'fecha': '2025-08-29', 'valor': 53.63}, {'fecha': '2025-08-28', 'valor': 55.63}, {'fecha': '2025-08-27', 'valor': 51.16}, {'fecha': '2025-08-26', 'valor': 53.85}, {'fecha': '2025-08-25', 'valor': 49.04}, {'fecha': '2025-08-22', 'valor': 48.6}, {'fecha': '2025-08-21', 'valor': 50.19}, {'fecha': '2025-08-20', 'valor': 52.81}, {'fecha': '2025-08-19', 'valor': 54.02}, {'fecha': '2025-08-18', 'valor': 46.5}, {'fecha': '2025-08-14', 'valor': 44.81}, {'fecha': '2025-08-13', 'valor': 42.8}, {'fecha': '2025-08-12', 'valor': 44.6}, {'fecha': '2025-08-11', 'valor': 39.05}, {'fecha': '2025-08-08', 'valor': 40.2}, {'fecha': '2025-08-07', 'valor': 37.15}, {'fecha': '2025-08-06', 'valor': 37.51}, {'fecha': '2025-08-05', 'valor': 37.66}, {'fecha': '2025-08-04', 'valor': 36.77}, {'fecha': '2025-08-01', 'valor': 36.03}, {'fecha': '2025-07-31', 'valor': 35.02}, {'fecha': '2025-07-30', 'valor': 33.46}, {'fecha': '2025-07-29', 'valor': 33.96}, {'fecha': '2025-07-28', 'valor': 32.1}, {'fecha': '2025-07-25', 'valor': 32.69}, {'fecha': '2025-07-24', 'valor': 32.77}, {'fecha': '2025-07-23', 'valor': 31.9}, {'fecha': '2025-07-22', 'valor': 33.06}, {'fecha': '2025-07-21', 'valor': 31.11}, {'fecha': '2025-07-18', 'valor': 29.81}, {'fecha': '2025-07-17', 'valor': 29.5}, {'fecha': '2025-07-16', 'valor': 29.77}, {'fecha': '2025-07-15', 'valor': 29.03}, {'fecha': '2025-07-14', 'valor': 29.1}, {'fecha': '2025-07-11', 'valor': 30.76}, {'fecha': '2025-07-10', 'valor': 31.04}, {'fecha': '2025-07-08', 'valor': 31.97}, {'fecha': '2025-07-07', 'valor': 31.66}, {'fecha': '2025-07-04', 'valor': 31.4}, {'fecha': '2025-07-03', 'valor': 32.36}, {'fecha': '2025-07-02', 'valor': 32.15}, {'fecha': '2025-07-01', 'valor': 32.6}, {'fecha': '2025-06-30', 'valor': 31.42}, {'fecha': '2025-06-27', 'valor': 31.06}, {'fecha': '2025-06-26', 'valor': 31.62}, {'fecha': '2025-06-25', 'valor': 31.77}, {'fecha': '2025-06-24', 'valor': 29.79}, {'fecha': '2025-06-23', 'valor': 31.0}, {'fecha': '2025-06-19', 'valor': 32.62}, {'fecha': '2025-06-18', 'valor': 31.39}, {'fecha': '2025-06-17', 'valor': 31.95}, {'fecha': '2025-06-13', 'valor': 31.51}, {'fecha': '2025-06-12', 'valor': 31.93}, {'fecha': '2025-06-11', 'valor': 31.8}, {'fecha': '2025-06-10', 'valor': 31.86}, {'fecha': '2025-06-09', 'valor': 31.29}, {'fecha': '2025-06-06', 'valor': 32.11}, {'fecha': '2025-06-05', 'valor': 32.1}, {'fecha': '2025-06-04', 'valor': 31.4}, {'fecha': '2025-06-03', 'valor': 32.82}, {'fecha': '2025-06-02', 'valor': 32.75}, {'fecha': '2025-05-30', 'valor': 31.29}, {'fecha': '2025-05-29', 'valor': 32.43}, {'fecha': '2025-05-28', 'valor': 31.39}, {'fecha': '2025-05-27', 'valor': 32.55}, {'fecha': '2025-05-26', 'valor': 31.55}, {'fecha': '2025-05-23', 'valor': 32.19}, {'fecha': '2025-05-22', 'valor': 31.97}, {'fecha': '2025-05-21', 'valor': 31.45}, {'fecha': '2025-05-20', 'valor': 33.18}, {'fecha': '2025-05-19', 'valor': 33.1}, {'fecha': '2025-05-16', 'valor': 32.2}, {'fecha': '2025-05-15', 'valor': 32.97}, {'fecha': '2025-05-14', 'valor': 32.06}, {'fecha': '2025-05-13', 'valor': 32.56}, {'fecha': '2025-05-12', 'valor': 32.04}, {'fecha': '2025-05-09', 'valor': 31.8}, {'fecha': '2025-05-08', 'valor': 32.63}, {'fecha': '2025-05-07', 'valor': 33.0}, {'fecha': '2025-05-06', 'valor': 33.55}, {'fecha': '2025-05-05', 'valor': 32.11}, {'fecha': '2025-04-30', 'valor': 32.44}, {'fecha': '2025-04-29', 'valor': 33.03}, {'fecha': '2025-04-28', 'valor': 32.66}, {'fecha': '2025-04-25', 'valor': 33.54}, {'fecha': '2025-04-24', 'valor': 33.12}, {'fecha': '2025-04-23', 'valor': 32.84}, {'fecha': '2025-04-22', 'valor': 33.87}, {'fecha': '2025-04-21', 'valor': 34.03}, {'fecha': '2025-04-16', 'valor': 36.87}, {'fecha': '2025-04-15', 'valor': 35.13}, {'fecha': '2025-04-14', 'valor': 34.02}, {'fecha': '2025-04-11', 'valor': 30.75}, {'fecha': '2025-04-10', 'valor': 30.6}, {'fecha': '2025-04-09', 'valor': 29.84}, {'fecha': '2025-04-08', 'valor': 31.03}, {'fecha': '2025-04-07', 'valor': 30.6}, {'fecha': '2025-04-04', 'valor': 29.66}, {'fecha': '2025-04-03', 'valor': 30.84}, {'fecha': '2025-04-01', 'valor': 31.07}, {'fecha': '2025-03-31', 'valor': 29.46}, {'fecha': '2025-03-28', 'valor': 28.82}, {'fecha': '2025-03-27', 'valor': 30.72}, {'fecha': '2025-03-26', 'valor': 29.3}, {'fecha': '2025-03-25', 'valor': 28.83}, {'fecha': '2025-03-21', 'valor': 28.57}, {'fecha': '2025-03-20', 'valor': 29.53}, {'fecha': '2025-03-19', 'valor': 29.67}, {'fecha': '2025-03-18', 'valor': 29.59}, {'fecha': '2025-03-17', 'valor': 28.07}, {'fecha': '2025-03-14', 'valor': 27.78}, {'fecha': '2025-03-13', 'valor': 28.23}, {'fecha': '2025-03-12', 'valor': 27.48}, {'fecha': '2025-03-11', 'valor': 27.79}, {'fecha': '2025-03-10', 'valor': 26.61}, {'fecha': '2025-03-07', 'valor': 28.4}, {'fecha': '2025-03-06', 'valor': 28.11}, {'fecha': '2025-03-05', 'valor': 26.65}, {'fecha': '2025-02-28', 'valor': 27.74}, {'fecha': '2025-02-27', 'valor': 27.3}, {'fecha': '2025-02-26', 'valor': 26.84}, {'fecha': '2025-02-25', 'valor': 27.95}, {'fecha': '2025-02-24', 'valor': 27.23}, {'fecha': '2025-02-21', 'valor': 27.32}, {'fecha': '2025-02-20', 'valor': 27.46}, {'fecha': '2025-02-19', 'valor': 27.03}, {'fecha': '2025-02-18', 'valor': 28.13}, {'fecha': '2025-02-17', 'valor': 27.86}, {'fecha': '2025-02-14', 'valor': 27.56}, {'fecha': '2025-02-13', 'valor': 27.16}, {'fecha': '2025-02-12', 'valor': 27.2}, {'fecha': '2025-02-11', 'valor': 28.13}, {'fecha': '2025-02-10', 'valor': 27.2}, {'fecha': '2025-02-07', 'valor': 27.0}, {'fecha': '2025-02-06', 'valor': 28.48}, {'fecha': '2025-02-05', 'valor': 28.51}, {'fecha': '2025-02-04', 'valor': 28.45}, {'fecha': '2025-02-03', 'valor': 26.99}, {'fecha': '2025-01-31', 'valor': 28.72}, {'fecha': '2025-01-30', 'valor': 31.2}, {'fecha': '2025-01-29', 'valor': 30.28}, {'fecha': '2025-01-28', 'valor': 31.42}, {'fecha': '2025-01-27', 'valor': 29.46}, {'fecha': '2025-01-24', 'valor': 30.97}, {'fecha': '2025-01-23', 'valor': 29.98}, {'fecha': '2025-01-22', 'valor': 30.34}, {'fecha': '2025-01-21', 'valor': 30.39}, {'fecha': '2025-01-20', 'valor': 29.82}, {'fecha': '2025-01-17', 'valor': 31.27}, {'fecha': '2025-01-16', 'valor': 30.13}, {'fecha': '2025-01-15', 'valor': 30.72}, {'fecha': '2025-01-14', 'valor': 32.28}, {'fecha': '2025-01-13', 'valor': 31.07}, {'fecha': '2025-01-10', 'valor': 31.55}, {'fecha': '2025-01-09', 'valor': 31.07}, {'fecha': '2025-01-08', 'valor': 30.32}, {'fecha': '2025-01-07', 'valor': 31.01}, {'fecha': '2025-01-06', 'valor': 31.59}, {'fecha': '2025-01-03', 'valor': 31.8}, {'fecha': '2025-01-02', 'valor': 31.42}, {'fecha': '2024-12-30', 'valor': 31.78}, {'fecha': '2024-12-27', 'valor': 32.13}, {'fecha': '2024-12-26', 'valor': 31.22}, {'fecha': '2024-12-23', 'valor': 31.56}, {'fecha': '2024-12-20', 'valor': 31.35}, {'fecha': '2024-12-19', 'valor': 30.85}, {'fecha': '2024-12-18', 'valor': 31.57}, {'fecha': '2024-12-17', 'valor': 31.86}, {'fecha': '2024-12-16', 'valor': 31.44}, {'fecha': '2024-12-13', 'valor': 31.32}, {'fecha': '2024-12-12', 'valor': 31.96}, {'fecha': '2024-12-11', 'valor': 30.64}, {'fecha': '2024-12-10', 'valor': 31.73}, {'fecha': '2024-12-09', 'valor': 30.94}, {'fecha': '2024-12-06', 'valor': 32.92}, {'fecha': '2024-12-05', 'valor': 35.16}, {'fecha': '2024-12-04', 'valor': 35.32}, {'fecha': '2024-12-03', 'valor': 35.98}, {'fecha': '2024-12-02', 'valor': 32.65}, {'fecha': '2024-11-29', 'valor': 36.59}, {'fecha': '2024-11-28', 'valor': 36.11}, {'fecha': '2024-11-27', 'valor': 35.67}, {'fecha': '2024-11-26', 'valor': 36.31}, {'fecha': '2024-11-25', 'valor': 34.73}, {'fecha': '2024-11-22', 'valor': 35.18}, {'fecha': '2024-11-21', 'valor': 36.57}, {'fecha': '2024-11-20', 'valor': 35.65}, {'fecha': '2024-11-19', 'valor': 33.8}, {'fecha': '2024-11-15', 'valor': 36.27}, {'fecha': '2024-11-14', 'valor': 35.93}, {'fecha': '2024-11-13', 'valor': 35.59}, {'fecha': '2024-11-12', 'valor': 36.17}, {'fecha': '2024-11-11', 'valor': 35.38}, {'fecha': '2024-11-08', 'valor': 34.88}, {'fecha': '2024-11-07', 'valor': 35.34}, {'fecha': '2024-11-05', 'valor': 36.33}, {'fecha': '2024-11-04', 'valor': 36.1}, {'fecha': '2024-11-01', 'valor': 36.7}, {'fecha': '2024-10-31', 'valor': 40.45}, {'fecha': '2024-10-30', 'valor': 39.47}, {'fecha': '2024-10-29', 'valor': 40.59}, {'fecha': '2024-10-28', 'valor': 39.08}, {'fecha': '2024-10-25', 'valor': 38.47}, {'fecha': '2024-10-24', 'valor': 39.88}, {'fecha': '2024-10-23', 'valor': 38.58}, {'fecha': '2024-10-22', 'valor': 41.12}, {'fecha': '2024-10-21', 'valor': 39.92}, {'fecha': '2024-10-18', 'valor': 38.71}, {'fecha': '2024-10-17', 'valor': 37.36}, {'fecha': '2024-10-16', 'valor': 39.29}, {'fecha': '2024-10-15', 'valor': 39.27}, {'fecha': '2024-10-14', 'valor': 38.97}, {'fecha': '2024-10-10', 'valor': 39.03}, {'fecha': '2024-10-09', 'valor': 38.04}, {'fecha': '2024-10-08', 'valor': 37.94}, {'fecha': '2024-10-07', 'valor': 38.89}, {'fecha': '2024-10-04', 'valor': 38.57}, {'fecha': '2024-10-03', 'valor': 39.52}, {'fecha': '2024-10-02', 'valor': 38.41}, {'fecha': '2024-10-01', 'valor': 37.61}, {'fecha': '2024-09-30', 'valor': 39.41}, {'fecha': '2024-09-27', 'valor': 39.29}, {'fecha': '2024-09-26', 'valor': 39.8}, {'fecha': '2024-09-25', 'valor': 38.21}, {'fecha': '2024-09-24', 'valor': 41.1}, {'fecha': '2024-09-23', 'valor': 38.8}, {'fecha': '2024-09-20', 'valor': 40.42}, {'fecha': '2024-09-19', 'valor': 39.5}, {'fecha': '2024-09-18', 'valor': 37.68}, {'fecha': '2024-09-17', 'valor': 35.22}, {'fecha': '2024-09-16', 'valor': 37.75}, {'fecha': '2024-09-13', 'valor': 37.88}, {'fecha': '2024-09-12', 'valor': 38.56}, {'fecha': '2024-09-11', 'valor': 38.71}, {'fecha': '2024-09-10', 'valor': 37.95}, {'fecha': '2024-09-09', 'valor': 37.16}, {'fecha': '2024-09-06', 'valor': 37.93}, {'fecha': '2024-09-05', 'valor': 38.32}, {'fecha': '2024-09-04', 'valor': 37.24}, {'fecha': '2024-09-03', 'valor': 37.3}, {'fecha': '2024-09-02', 'valor': 37.43}, {'fecha': '2024-08-30', 'valor': 41.21}, {'fecha': '2024-08-29', 'valor': 39.51}, {'fecha': '2024-08-28', 'valor': 38.02}, {'fecha': '2024-08-27', 'valor': 39.18}, {'fecha': '2024-08-26', 'valor': 37.48}, {'fecha': '2024-08-23', 'valor': 37.57}, {'fecha': '2024-08-22', 'valor': 40.34}, {'fecha': '2024-08-21', 'valor': 38.22}, {'fecha': '2024-08-20', 'valor': 39.23}, {'fecha': '2024-08-19', 'valor': 37.45}, {'fecha': '2024-08-16', 'valor': 37.06}, {'fecha': '2024-08-15', 'valor': 37.0}, {'fecha': '2024-08-14', 'valor': 37.79}, {'fecha': '2024-08-13', 'valor': 38.75}, {'fecha': '2024-08-12', 'valor': 37.51}, {'fecha': '2024-08-09', 'valor': 37.22}, {'fecha': '2024-08-08', 'valor': 37.16}, {'fecha': '2024-08-07', 'valor': 36.58}, {'fecha': '2024-08-06', 'valor': 38.37}, {'fecha': '2024-08-05', 'valor': 36.45}, {'fecha': '2024-08-02', 'valor': 36.84}, {'fecha': '2024-08-01', 'valor': 37.3}, {'fecha': '2024-07-31', 'valor': 35.69}, {'fecha': '2024-07-30', 'valor': 37.61}, {'fecha': '2024-07-29', 'valor': 36.67}, {'fecha': '2024-07-26', 'valor': 35.48}, {'fecha': '2024-07-25', 'valor': 35.68}, {'fecha': '2024-07-24', 'valor': 36.11}, {'fecha': '2024-07-23', 'valor': 39.35}, {'fecha': '2024-07-22', 'valor': 36.67}, {'fecha': '2024-07-19', 'valor': 35.98}, {'fecha': '2024-07-18', 'valor': 35.14}, {'fecha': '2024-07-17', 'valor': 37.36}, {'fecha': '2024-07-16', 'valor': 35.6}, {'fecha': '2024-07-15', 'valor': 34.84}, {'fecha': '2024-07-12', 'valor': 36.16}, {'fecha': '2024-07-11', 'valor': 34.55}, {'fecha': '2024-07-10', 'valor': 33.72}, {'fecha': '2024-07-08', 'valor': 35.4}, {'fecha': '2024-07-05', 'valor': 34.4}, {'fecha': '2024-07-04', 'valor': 35.66}, {'fecha': '2024-07-03', 'valor': 34.27}, {'fecha': '2024-07-02', 'valor': 34.09}, {'fecha': '2024-07-01', 'valor': 34.45}, {'fecha': '2024-06-28', 'valor': 35.02}, {'fecha': '2024-06-27', 'valor': 33.18}, {'fecha': '2024-06-26', 'valor': 32.36}, {'fecha': '2024-06-25', 'valor': 33.89}, {'fecha': '2024-06-24', 'valor': 32.8}, {'fecha': '2024-06-19', 'valor': 32.69}, {'fecha': '2024-06-18', 'valor': 31.3}, {'fecha': '2024-06-14', 'valor': 31.28}, {'fecha': '2024-06-13', 'valor': 32.73}, {'fecha': '2024-06-12', 'valor': 32.53}, {'fecha': '2024-06-11', 'valor': 33.29}, {'fecha': '2024-06-10', 'valor': 30.65}, {'fecha': '2024-06-07', 'valor': 31.9}, {'fecha': '2024-06-06', 'valor': 32.28}, {'fecha': '2024-06-05', 'valor': 31.22}, {'fecha': '2024-06-04', 'valor': 30.85}, {'fecha': '2024-06-03', 'valor': 31.09}, {'fecha': '2024-05-31', 'valor': 31.0}, {'fecha': '2024-05-30', 'valor': 32.18}, {'fecha': '2024-05-29', 'valor': 31.46}, {'fecha': '2024-05-28', 'valor': 31.17}, {'fecha': '2024-05-27', 'valor': 30.9}, {'fecha': '2024-05-24', 'valor': 30.68}, {'fecha': '2024-05-23', 'valor': 30.86}, {'fecha': '2024-05-22', 'valor': 30.34}, {'fecha': '2024-05-21', 'valor': 30.96}, {'fecha': '2024-05-20', 'valor': 31.2}, {'fecha': '2024-05-17', 'valor': 30.18}, {'fecha': '2024-05-16', 'valor': 31.39}, {'fecha': '2024-05-15', 'valor': 30.87}, {'fecha': '2024-05-14', 'valor': 39.08}, {'fecha': '2024-05-13', 'valor': 39.19}, {'fecha': '2024-05-10', 'valor': 39.23}, {'fecha': '2024-05-09', 'valor': 39.63}, {'fecha': '2024-05-08', 'valor': 39.64}, {'fecha': '2024-05-07', 'valor': 40.15}, {'fecha': '2024-05-06', 'valor': 39.53}, {'fecha': '2024-05-03', 'valor': 40.38}, {'fecha': '2024-05-02', 'valor': 48.24}, {'fecha': '2024-04-30', 'valor': 51.02}, {'fecha': '2024-04-29', 'valor': 50.47}, {'fecha': '2024-04-26', 'valor': 50.08}, {'fecha': '2024-04-25', 'valor': 57.16}, {'fecha': '2024-04-24', 'valor': 60.09}, {'fecha': '2024-04-23', 'valor': 60.66}, {'fecha': '2024-04-22', 'valor': 60.48}, {'fecha': '2024-04-19', 'valor': 60.17}, {'fecha': '2024-04-18', 'valor': 60.81}, {'fecha': '2024-04-17', 'valor': 60.24}, {'fecha': '2024-04-16', 'valor': 60.76}, {'fecha': '2024-04-15', 'valor': 59.26}, {'fecha': '2024-04-12', 'valor': 60.85}, {'fecha': '2024-04-11', 'valor': 66.25}, {'fecha': '2024-04-10', 'valor': 67.92}, {'fecha': '2024-04-09', 'valor': 68.98}, {'fecha': '2024-04-08', 'valor': 70.39}, {'fecha': '2024-04-05', 'valor': 70.34}, {'fecha': '2024-04-04', 'valor': 69.51}, {'fecha': '2024-04-03', 'valor': 70.05}, {'fecha': '2024-03-27', 'valor': 70.2}, {'fecha': '2024-03-26', 'valor': 70.64}, {'fecha': '2024-03-25', 'valor': 70.74}, {'fecha': '2024-03-22', 'valor': 70.41}, {'fecha': '2024-03-21', 'valor': 71.44}, {'fecha': '2024-03-20', 'valor': 70.66}, {'fecha': '2024-03-19', 'valor': 70.87}, {'fecha': '2024-03

El BCRA publica el promedio del plazo fijo con un `día de rezago`. 
EL primer valor refleja la tasa del día de ayer (d-1).

In [5]:
print(len(data_monetaria["results"])) #q de elementos de results

1

In [6]:
data_monetaria["results"][0]["detalle"]

[{'fecha': '2026-03-27', 'valor': 23.9},
 {'fecha': '2026-03-26', 'valor': 25.1},
 {'fecha': '2026-03-25', 'valor': 24.88},
 {'fecha': '2026-03-20', 'valor': 24.97},
 {'fecha': '2026-03-19', 'valor': 25.95},
 {'fecha': '2026-03-18', 'valor': 26.31},
 {'fecha': '2026-03-17', 'valor': 27.18},
 {'fecha': '2026-03-16', 'valor': 27.39},
 {'fecha': '2026-03-13', 'valor': 27.16},
 {'fecha': '2026-03-12', 'valor': 27.81},
 {'fecha': '2026-03-11', 'valor': 27.28},
 {'fecha': '2026-03-10', 'valor': 28.27},
 {'fecha': '2026-03-09', 'valor': 27.66},
 {'fecha': '2026-03-06', 'valor': 27.5},
 {'fecha': '2026-03-05', 'valor': 27.27},
 {'fecha': '2026-03-04', 'valor': 27.37},
 {'fecha': '2026-03-03', 'valor': 27.88},
 {'fecha': '2026-03-02', 'valor': 28.08},
 {'fecha': '2026-02-27', 'valor': 28.28},
 {'fecha': '2026-02-26', 'valor': 29.12},
 {'fecha': '2026-02-25', 'valor': 28.04},
 {'fecha': '2026-02-24', 'valor': 31.82},
 {'fecha': '2026-02-23', 'valor': 30.16},
 {'fecha': '2026-02-20', 'valor': 30.75},
 {'fecha': '2026-02-19', 'valor': 30.34},
 {'fecha': '2026-02-18', 'valor': 28.91},
 {'fecha': '2026-02-13', 'valor': 28.18},
 {'fecha': '2026-02-12', 'valor': 28.04},
 {'fecha': '2026-02-11', 'valor': 27.11},
 {'fecha': '2026-02-10', 'valor': 28.63},
 {'fecha': '2026-02-09', 'valor': 27.86},
 {'fecha': '2026-02-06', 'valor': 28.52},
 {'fecha': '2026-02-05', 'valor': 29.14},
 {'fecha': '2026-02-04', 'valor': 28.51},
 {'fecha': '2026-02-03', 'valor': 30.13},
 {'fecha': '2026-02-02', 'valor': 28.21},
 {'fecha': '2026-01-30', 'valor': 28.57},
 {'fecha': '2026-01-29', 'valor': 28.62},
 {'fecha': '2026-01-28', 'valor': 29.29},
 {'fecha': '2026-01-27', 'valor': 31.28},
 {'fecha': '2026-01-26', 'valor': 29.29},
 {'fecha': '2026-01-23', 'valor': 33.06},
 {'fecha': '2026-01-22', 'valor': 32.93},
 {'fecha': '2026-01-21', 'valor': 30.67},
 {'fecha': '2026-01-20', 'valor': 30.87},
 {'fecha': '2026-01-19', 'valor': 30.02},
 {'fecha': '2026-01-16', 'valor': 29.93},
 {'fecha': '2026-01-15', 'valor': 29.88},
 {'fecha': '2026-01-14', 'valor': 28.78},
 {'fecha': '2026-01-13', 'valor': 28.56},
 {'fecha': '2026-01-12', 'valor': 25.86},
 {'fecha': '2026-01-09', 'valor': 26.37},
 {'fecha': '2026-01-08', 'valor': 27.55},
 {'fecha': '2026-01-07', 'valor': 28.43},
 {'fecha': '2026-01-06', 'valor': 26.64},
 {'fecha': '2026-01-05', 'valor': 25.64},
 {'fecha': '2026-01-02', 'valor': 25.22},
 {'fecha': '2025-12-30', 'valor': 25.46},
 {'fecha': '2025-12-29', 'valor': 25.29},
 {'fecha': '2025-12-26', 'valor': 25.38},
 {'fecha': '2025-12-23', 'valor': 27.44},
 {'fecha': '2025-12-22', 'valor': 26.04},
 {'fecha': '2025-12-19', 'valor': 25.63},
 {'fecha': '2025-12-18', 'valor': 25.12},
 {'fecha': '2025-12-17', 'valor': 25.0},
 {'fecha': '2025-12-16', 'valor': 24.92},
 {'fecha': '2025-12-15', 'valor': 24.8},
 {'fecha': '2025-12-12', 'valor': 24.24},
 {'fecha': '2025-12-11', 'valor': 24.52},
 {'fecha': '2025-12-10', 'valor': 24.73},
 {'fecha': '2025-12-09', 'valor': 24.93},
 {'fecha': '2025-12-05', 'valor': 25.56},
 {'fecha': '2025-12-04', 'valor': 25.68},
 {'fecha': '2025-12-03', 'valor': 26.47},
 {'fecha': '2025-12-02', 'valor': 28.41},
 {'fecha': '2025-12-01', 'valor': 28.06},
 {'fecha': '2025-11-28', 'valor': 29.03},
 {'fecha': '2025-11-27', 'valor': 29.06},
 {'fecha': '2025-11-26', 'valor': 28.91},
 {'fecha': '2025-11-25', 'valor': 29.32},
 {'fecha': '2025-11-20', 'valor': 30.62},
 {'fecha': '2025-11-19', 'valor': 31.19},
 {'fecha': '2025-11-18', 'valor': 30.55},
 {'fecha': '2025-11-17', 'valor': 30.27},
 {'fecha': '2025-11-14', 'valor': 30.7},
 {'fecha': '2025-11-13', 'valor': 30.97},
 {'fecha': '2025-11-12', 'valor': 30.88},
 {'fecha': '2025-11-11', 'valor': 32.73},
 {'fecha': '2025-11-10', 'valor': 32.01},
 {'fecha': '2025-11-07', 'valor': 33.05},
 {'fecha': '2025-11-05', 'valor': 34.17},
 {'fecha': '2025-11-04', 'valor': 35.94},
 {'fecha': '2025-11-03', 'valor': 35.06},
 {'fecha': '2025-10-31', 'valor': 37.49},
 {'fecha': '2025-10-30', 'valor': 39.32},
 {'fecha': '2025-10-29', 'valor': 40.91},
 {'fecha': '2025-10-28', 'valor': 44.82},
 {'fecha': '2025-10-27', 'valor': 43.3},
 {'fecha': '2025-10-24', 'valor': 47.12},
 {'fecha': '2025-10-23', 'valor': 47.06},
 {'fecha': '2025-10-22', 'valor': 47.09},
 {'fecha': '2025-10-21', 'valor': 48.77},
 {'fecha': '2025-10-20', 'valor': 48.28},
 {'fecha': '2025-10-17', 'valor': 49.45},
 {'fecha': '2025-10-16', 'valor': 54.44},
 {'fecha': '2025-10-15', 'valor': 51.47},
 {'fecha': '2025-10-14', 'valor': 49.38},
 {'fecha': '2025-10-13', 'valor': 45.44},
 {'fecha': '2025-10-09', 'valor': 46.08},
 {'fecha': '2025-10-08', 'valor': 41.85},
 {'fecha': '2025-10-07', 'valor': 42.3},
 {'fecha': '2025-10-06', 'valor': 39.98},
 {'fecha': '2025-10-03', 'valor': 39.49},
 {'fecha': '2025-10-02', 'valor': 39.93},
 {'fecha': '2025-10-01', 'valor': 40.17},
 {'fecha': '2025-09-30', 'valor': 37.67},
 {'fecha': '2025-09-29', 'valor': 38.8},
 {'fecha': '2025-09-26', 'valor': 37.78},
 {'fecha': '2025-09-25', 'valor': 39.22},
 {'fecha': '2025-09-24', 'valor': 43.22},
 {'fecha': '2025-09-23', 'valor': 45.64},
 {'fecha': '2025-09-22', 'valor': 43.72},
 {'fecha': '2025-09-19', 'valor': 43.78},
 {'fecha': '2025-09-18', 'valor': 43.89},
 {'fecha': '2025-09-17', 'valor': 43.03},
 {'fecha': '2025-09-16', 'valor': 43.34},
 {'fecha': '2025-09-15', 'valor': 44.71},
 {'fecha': '2025-09-12', 'valor': 45.42},
 {'fecha': '2025-09-11', 'valor': 49.43},
 {'fecha': '2025-09-10', 'valor': 51.16},
 {'fecha': '2025-09-09', 'valor': 55.64},
 {'fecha': '2025-09-08', 'valor': 53.62},
 {'fecha': '2025-09-05', 'valor': 52.72},
 {'fecha': '2025-09-04', 'valor': 56.06},
 {'fecha': '2025-09-03', 'valor': 52.49},
 {'fecha': '2025-09-02', 'valor': 53.62},
 {'fecha': '2025-09-01', 'valor': 54.57},
 {'fecha': '2025-08-29', 'valor': 53.63},
 {'fecha': '2025-08-28', 'valor': 55.63},
 {'fecha': '2025-08-27', 'valor': 51.16},
 {'fecha': '2025-08-26', 'valor': 53.85},
 {'fecha': '2025-08-25', 'valor': 49.04},
 {'fecha': '2025-08-22', 'valor': 48.6},
 {'fecha': '2025-08-21', 'valor': 50.19},
 {'fecha': '2025-08-20', 'valor': 52.81},
 {'fecha': '2025-08-19', 'valor': 54.02},
 {'fecha': '2025-08-18', 'valor': 46.5},
 {'fecha': '2025-08-14', 'valor': 44.81},
 {'fecha': '2025-08-13', 'valor': 42.8},
 {'fecha': '2025-08-12', 'valor': 44.6},
 {'fecha': '2025-08-11', 'valor': 39.05},
 {'fecha': '2025-08-08', 'valor': 40.2},
 {'fecha': '2025-08-07', 'valor': 37.15},
 {'fecha': '2025-08-06', 'valor': 37.51},
 {'fecha': '2025-08-05', 'valor': 37.66},
 {'fecha': '2025-08-04', 'valor': 36.77},
 {'fecha': '2025-08-01', 'valor': 36.03},
 {'fecha': '2025-07-31', 'valor': 35.02},
 {'fecha': '2025-07-30', 'valor': 33.46},
 {'fecha': '2025-07-29', 'valor': 33.96},
 {'fecha': '2025-07-28', 'valor': 32.1},
 {'fecha': '2025-07-25', 'valor': 32.69},
 {'fecha': '2025-07-24', 'valor': 32.77},
 {'fecha': '2025-07-23', 'valor': 31.9},
 {'fecha': '2025-07-22', 'valor': 33.06},
 {'fecha': '2025-07-21', 'valor': 31.11},
 {'fecha': '2025-07-18', 'valor': 29.81},
 {'fecha': '2025-07-17', 'valor': 29.5},
 {'fecha': '2025-07-16', 'valor': 29.77},
 {'fecha': '2025-07-15', 'valor': 29.03},
 {'fecha': '2025-07-14', 'valor': 29.1},
 {'fecha': '2025-07-11', 'valor': 30.76},
 {'fecha': '2025-07-10', 'valor': 31.04},
 {'fecha': '2025-07-08', 'valor': 31.97},
 {'fecha': '2025-07-07', 'valor': 31.66},
 {'fecha': '2025-07-04', 'valor': 31.4},
 {'fecha': '2025-07-03', 'valor': 32.36},
 {'fecha': '2025-07-02', 'valor': 32.15},
 {'fecha': '2025-07-01', 'valor': 32.6},
 {'fecha': '2025-06-30', 'valor': 31.42},
 {'fecha': '2025-06-27', 'valor': 31.06},
 {'fecha': '2025-06-26', 'valor': 31.62},
 {'fecha': '2025-06-25', 'valor': 31.77},
 {'fecha': '2025-06-24', 'valor': 29.79},
 {'fecha': '2025-06-23', 'valor': 31.0},
 {'fecha': '2025-06-19', 'valor': 32.62},
 {'fecha': '2025-06-18', 'valor': 31.39},
 {'fecha': '2025-06-17', 'valor': 31.95},
 {'fecha': '2025-06-13', 'valor': 31.51},
 {'fecha': '2025-06-12', 'valor': 31.93},
 {'fecha': '2025-06-11', 'valor': 31.8},
 {'fecha': '2025-06-10', 'valor': 31.86},
 {'fecha': '2025-06-09', 'valor': 31.29},
 {'fecha': '2025-06-06', 'valor': 32.11},
 {'fecha': '2025-06-05', 'valor': 32.1},
 {'fecha': '2025-06-04', 'valor': 31.4},
 {'fecha': '2025-06-03', 'valor': 32.82},
 {'fecha': '2025-06-02', 'valor': 32.75},
 {'fecha': '2025-05-30', 'valor': 31.29},
 {'fecha': '2025-05-29', 'valor': 32.43},
 {'fecha': '2025-05-28', 'valor': 31.39},
 {'fecha': '2025-05-27', 'valor': 32.55},
 {'fecha': '2025-05-26', 'valor': 31.55},
 {'fecha': '2025-05-23', 'valor': 32.19},
 {'fecha': '2025-05-22', 'valor': 31.97},
 {'fecha': '2025-05-21', 'valor': 31.45},
 {'fecha': '2025-05-20', 'valor': 33.18},
 {'fecha': '2025-05-19', 'valor': 33.1},
 {'fecha': '2025-05-16', 'valor': 32.2},
 {'fecha': '2025-05-15', 'valor': 32.97},
 {'fecha': '2025-05-14', 'valor': 32.06},
 {'fecha': '2025-05-13', 'valor': 32.56},
 {'fecha': '2025-05-12', 'valor': 32.04},
 {'fecha': '2025-05-09', 'valor': 31.8},
 {'fecha': '2025-05-08', 'valor': 32.63},
 {'fecha': '2025-05-07', 'valor': 33.0},
 {'fecha': '2025-05-06', 'valor': 33.55},
 {'fecha': '2025-05-05', 'valor': 32.11},
 {'fecha': '2025-04-30', 'valor': 32.44},
 {'fecha': '2025-04-29', 'valor': 33.03},
 {'fecha': '2025-04-28', 'valor': 32.66},
 {'fecha': '2025-04-25', 'valor': 33.54},
 {'fecha': '2025-04-24', 'valor': 33.12},
 {'fecha': '2025-04-23', 'valor': 32.84},
 {'fecha': '2025-04-22', 'valor': 33.87},
 {'fecha': '2025-04-21', 'valor': 34.03},
 {'fecha': '2025-04-16', 'valor': 36.87},
 {'fecha': '2025-04-15', 'valor': 35.13},
 {'fecha': '2025-04-14', 'valor': 34.02},
 {'fecha': '2025-04-11', 'valor': 30.75},
 {'fecha': '2025-04-10', 'valor': 30.6},
 {'fecha': '2025-04-09', 'valor': 29.84},
 {'fecha': '2025-04-08', 'valor': 31.03},
 {'fecha': '2025-04-07', 'valor': 30.6},
 {'fecha': '2025-04-04', 'valor': 29.66},
 {'fecha': '2025-04-03', 'valor': 30.84},
 {'fecha': '2025-04-01', 'valor': 31.07},
 {'fecha': '2025-03-31', 'valor': 29.46},
 {'fecha': '2025-03-28', 'valor': 28.82},
 {'fecha': '2025-03-27', 'valor': 30.72},
 {'fecha': '2025-03-26', 'valor': 29.3},
 {'fecha': '2025-03-25', 'valor': 28.83},
 {'fecha': '2025-03-21', 'valor': 28.57},
 {'fecha': '2025-03-20', 'valor': 29.53},
 {'fecha': '2025-03-19', 'valor': 29.67},
 {'fecha': '2025-03-18', 'valor': 29.59},
 {'fecha': '2025-03-17', 'valor': 28.07},
 {'fecha': '2025-03-14', 'valor': 27.78},
 {'fecha': '2025-03-13', 'valor': 28.23},
 {'fecha': '2025-03-12', 'valor': 27.48},
 {'fecha': '2025-03-11', 'valor': 27.79},
 {'fecha': '2025-03-10', 'valor': 26.61},
 {'fecha': '2025-03-07', 'valor': 28.4},
 {'fecha': '2025-03-06', 'valor': 28.11},
 {'fecha': '2025-03-05', 'valor': 26.65},
 {'fecha': '2025-02-28', 'valor': 27.74},
 {'fecha': '2025-02-27', 'valor': 27.3},
 {'fecha': '2025-02-26', 'valor': 26.84},
 {'fecha': '2025-02-25', 'valor': 27.95},
 {'fecha': '2025-02-24', 'valor': 27.23},
 {'fecha': '2025-02-21', 'valor': 27.32},
 {'fecha': '2025-02-20', 'valor': 27.46},
 {'fecha': '2025-02-19', 'valor': 27.03},
 {'fecha': '2025-02-18', 'valor': 28.13},
 {'fecha': '2025-02-17', 'valor': 27.86},
 {'fecha': '2025-02-14', 'valor': 27.56},
 {'fecha': '2025-02-13', 'valor': 27.16},
 {'fecha': '2025-02-12', 'valor': 27.2},
 {'fecha': '2025-02-11', 'valor': 28.13},
 {'fecha': '2025-02-10', 'valor': 27.2},
 {'fecha': '2025-02-07', 'valor': 27.0},
 {'fecha': '2025-02-06', 'valor': 28.48},
 {'fecha': '2025-02-05', 'valor': 28.51},
 {'fecha': '2025-02-04', 'valor': 28.45},
 {'fecha': '2025-02-03', 'valor': 26.99},
 {'fecha': '2025-01-31', 'valor': 28.72},
 {'fecha': '2025-01-30', 'valor': 31.2},
 {'fecha': '2025-01-29', 'valor': 30.28},
 {'fecha': '2025-01-28', 'valor': 31.42},
 {'fecha': '2025-01-27', 'valor': 29.46},
 {'fecha': '2025-01-24', 'valor': 30.97},
 {'fecha': '2025-01-23', 'valor': 29.98},
 {'fecha': '2025-01-22', 'valor': 30.34},
 {'fecha': '2025-01-21', 'valor': 30.39},
 {'fecha': '2025-01-20', 'valor': 29.82},
 {'fecha': '2025-01-17', 'valor': 31.27},
 {'fecha': '2025-01-16', 'valor': 30.13},
 {'fecha': '2025-01-15', 'valor': 30.72},
 {'fecha': '2025-01-14', 'valor': 32.28},
 {'fecha': '2025-01-13', 'valor': 31.07},
 {'fecha': '2025-01-10', 'valor': 31.55},
 {'fecha': '2025-01-09', 'valor': 31.07},
 {'fecha': '2025-01-08', 'valor': 30.32},
 {'fecha': '2025-01-07', 'valor': 31.01},
 {'fecha': '2025-01-06', 'valor': 31.59},
 {'fecha': '2025-01-03', 'valor': 31.8},
 {'fecha': '2025-01-02', 'valor': 31.42},
 {'fecha': '2024-12-30', 'valor': 31.78},
 {'fecha': '2024-12-27', 'valor': 32.13},
 {'fecha': '2024-12-26', 'valor': 31.22},
 {'fecha': '2024-12-23', 'valor': 31.56},
 {'fecha': '2024-12-20', 'valor': 31.35},
 {'fecha': '2024-12-19', 'valor': 30.85},
 {'fecha': '2024-12-18', 'valor': 31.57},
 {'fecha': '2024-12-17', 'valor': 31.86},
 {'fecha': '2024-12-16', 'valor': 31.44},
 {'fecha': '2024-12-13', 'valor': 31.32},
 {'fecha': '2024-12-12', 'valor': 31.96},
 {'fecha': '2024-12-11', 'valor': 30.64},
 {'fecha': '2024-12-10', 'valor': 31.73},
 {'fecha': '2024-12-09', 'valor': 30.94},
 {'fecha': '2024-12-06', 'valor': 32.92},
 {'fecha': '2024-12-05', 'valor': 35.16},
 {'fecha': '2024-12-04', 'valor': 35.32},
 {'fecha': '2024-12-03', 'valor': 35.98},
 {'fecha': '2024-12-02', 'valor': 32.65},
 {'fecha': '2024-11-29', 'valor': 36.59},
 {'fecha': '2024-11-28', 'valor': 36.11},
 {'fecha': '2024-11-27', 'valor': 35.67},
 {'fecha': '2024-11-26', 'valor': 36.31},
 {'fecha': '2024-11-25', 'valor': 34.73},
 {'fecha': '2024-11-22', 'valor': 35.18},
 {'fecha': '2024-11-21', 'valor': 36.57},
 {'fecha': '2024-11-20', 'valor': 35.65},
 {'fecha': '2024-11-19', 'valor': 33.8},
 {'fecha': '2024-11-15', 'valor': 36.27},
 {'fecha': '2024-11-14', 'valor': 35.93},
 {'fecha': '2024-11-13', 'valor': 35.59},
 {'fecha': '2024-11-12', 'valor': 36.17},
 {'fecha': '2024-11-11', 'valor': 35.38},
 {'fecha': '2024-11-08', 'valor': 34.88},
 {'fecha': '2024-11-07', 'valor': 35.34},
 {'fecha': '2024-11-05', 'valor': 36.33},
 {'fecha': '2024-11-04', 'valor': 36.1},
 {'fecha': '2024-11-01', 'valor': 36.7},
 {'fecha': '2024-10-31', 'valor': 40.45},
 {'fecha': '2024-10-30', 'valor': 39.47},
 {'fecha': '2024-10-29', 'valor': 40.59},
 {'fecha': '2024-10-28', 'valor': 39.08},
 {'fecha': '2024-10-25', 'valor': 38.47},
 {'fecha': '2024-10-24', 'valor': 39.88},
 {'fecha': '2024-10-23', 'valor': 38.58},
 {'fecha': '2024-10-22', 'valor': 41.12},
 {'fecha': '2024-10-21', 'valor': 39.92},
 {'fecha': '2024-10-18', 'valor': 38.71},
 {'fecha': '2024-10-17', 'valor': 37.36},
 {'fecha': '2024-10-16', 'valor': 39.29},
 {'fecha': '2024-10-15', 'valor': 39.27},
 {'fecha': '2024-10-14', 'valor': 38.97},
 {'fecha': '2024-10-10', 'valor': 39.03},
 {'fecha': '2024-10-09', 'valor': 38.04},
 {'fecha': '2024-10-08', 'valor': 37.94},
 {'fecha': '2024-10-07', 'valor': 38.89},
 {'fecha': '2024-10-04', 'valor': 38.57},
 {'fecha': '2024-10-03', 'valor': 39.52},
 {'fecha': '2024-10-02', 'valor': 38.41},
 {'fecha': '2024-10-01', 'valor': 37.61},
 {'fecha': '2024-09-30', 'valor': 39.41},
 {'fecha': '2024-09-27', 'valor': 39.29},
 {'fecha': '2024-09-26', 'valor': 39.8},
 {'fecha': '2024-09-25', 'valor': 38.21},
 {'fecha': '2024-09-24', 'valor': 41.1},
 {'fecha': '2024-09-23', 'valor': 38.8},
 {'fecha': '2024-09-20', 'valor': 40.42},
 {'fecha': '2024-09-19', 'valor': 39.5},
 {'fecha': '2024-09-18', 'valor': 37.68},
 {'fecha': '2024-09-17', 'valor': 35.22},
 {'fecha': '2024-09-16', 'valor': 37.75},
 {'fecha': '2024-09-13', 'valor': 37.88},
 {'fecha': '2024-09-12', 'valor': 38.56},
 {'fecha': '2024-09-11', 'valor': 38.71},
 {'fecha': '2024-09-10', 'valor': 37.95},
 {'fecha': '2024-09-09', 'valor': 37.16},
 {'fecha': '2024-09-06', 'valor': 37.93},
 {'fecha': '2024-09-05', 'valor': 38.32},
 {'fecha': '2024-09-04', 'valor': 37.24},
 {'fecha': '2024-09-03', 'valor': 37.3},
 {'fecha': '2024-09-02', 'valor': 37.43},
 {'fecha': '2024-08-30', 'valor': 41.21},
 {'fecha': '2024-08-29', 'valor': 39.51},
 {'fecha': '2024-08-28', 'valor': 38.02},
 {'fecha': '2024-08-27', 'valor': 39.18},
 {'fecha': '2024-08-26', 'valor': 37.48},
 {'fecha': '2024-08-23', 'valor': 37.57},
 {'fecha': '2024-08-22', 'valor': 40.34},
 {'fecha': '2024-08-21', 'valor': 38.22},
 {'fecha': '2024-08-20', 'valor': 39.23},
 {'fecha': '2024-08-19', 'valor': 37.45},
 {'fecha': '2024-08-16', 'valor': 37.06},
 {'fecha': '2024-08-15', 'valor': 37.0},
 {'fecha': '2024-08-14', 'valor': 37.79},
 {'fecha': '2024-08-13', 'valor': 38.75},
 {'fecha': '2024-08-12', 'valor': 37.51},
 {'fecha': '2024-08-09', 'valor': 37.22},
 {'fecha': '2024-08-08', 'valor': 37.16},
 {'fecha': '2024-08-07', 'valor': 36.58},
 {'fecha': '2024-08-06', 'valor': 38.37},
 {'fecha': '2024-08-05', 'valor': 36.45},
 {'fecha': '2024-08-02', 'valor': 36.84},
 {'fecha': '2024-08-01', 'valor': 37.3},
 {'fecha': '2024-07-31', 'valor': 35.69},
 {'fecha': '2024-07-30', 'valor': 37.61},
 {'fecha': '2024-07-29', 'valor': 36.67},
 {'fecha': '2024-07-26', 'valor': 35.48},
 {'fecha': '2024-07-25', 'valor': 35.68},
 {'fecha': '2024-07-24', 'valor': 36.11},
 {'fecha': '2024-07-23', 'valor': 39.35},
 {'fecha': '2024-07-22', 'valor': 36.67},
 {'fecha': '2024-07-19', 'valor': 35.98},
 {'fecha': '2024-07-18', 'valor': 35.14},
 {'fecha': '2024-07-17', 'valor': 37.36},
 {'fecha': '2024-07-16', 'valor': 35.6},
 {'fecha': '2024-07-15', 'valor': 34.84},
 {'fecha': '2024-07-12', 'valor': 36.16},
 {'fecha': '2024-07-11', 'valor': 34.55},
 {'fecha': '2024-07-10', 'valor': 33.72},
 {'fecha': '2024-07-08', 'valor': 35.4},
 {'fecha': '2024-07-05', 'valor': 34.4},
 {'fecha': '2024-07-04', 'valor': 35.66},
 {'fecha': '2024-07-03', 'valor': 34.27},
 {'fecha': '2024-07-02', 'valor': 34.09},
 {'fecha': '2024-07-01', 'valor': 34.45},
 {'fecha': '2024-06-28', 'valor': 35.02},
 {'fecha': '2024-06-27', 'valor': 33.18},
 {'fecha': '2024-06-26', 'valor': 32.36},
 {'fecha': '2024-06-25', 'valor': 33.89},
 {'fecha': '2024-06-24', 'valor': 32.8},
 {'fecha': '2024-06-19', 'valor': 32.69},
 {'fecha': '2024-06-18', 'valor': 31.3},
 {'fecha': '2024-06-14', 'valor': 31.28},
 {'fecha': '2024-06-13', 'valor': 32.73},
 {'fecha': '2024-06-12', 'valor': 32.53},
 {'fecha': '2024-06-11', 'valor': 33.29},
 {'fecha': '2024-06-10', 'valor': 30.65},
 {'fecha': '2024-06-07', 'valor': 31.9},
 {'fecha': '2024-06-06', 'valor': 32.28},
 {'fecha': '2024-06-05', 'valor': 31.22},
 {'fecha': '2024-06-04', 'valor': 30.85},
 {'fecha': '2024-06-03', 'valor': 31.09},
 {'fecha': '2024-05-31', 'valor': 31.0},
 {'fecha': '2024-05-30', 'valor': 32.18},
 {'fecha': '2024-05-29', 'valor': 31.46},
 {'fecha': '2024-05-28', 'valor': 31.17},
 {'fecha': '2024-05-27', 'valor': 30.9},
 {'fecha': '2024-05-24', 'valor': 30.68},
 {'fecha': '2024-05-23', 'valor': 30.86},
 {'fecha': '2024-05-22', 'valor': 30.34},
 {'fecha': '2024-05-21', 'valor': 30.96},
 {'fecha': '2024-05-20', 'valor': 31.2},
 {'fecha': '2024-05-17', 'valor': 30.18},
 {'fecha': '2024-05-16', 'valor': 31.39},
 {'fecha': '2024-05-15', 'valor': 30.87},
 {'fecha': '2024-05-14', 'valor': 39.08},
 {'fecha': '2024-05-13', 'valor': 39.19},
 {'fecha': '2024-05-10', 'valor': 39.23},
 {'fecha': '2024-05-09', 'valor': 39.63},
 {'fecha': '2024-05-08', 'valor': 39.64},
 {'fecha': '2024-05-07', 'valor': 40.15},
 {'fecha': '2024-05-06', 'valor': 39.53},
 {'fecha': '2024-05-03', 'valor': 40.38},
 {'fecha': '2024-05-02', 'valor': 48.24},
 {'fecha': '2024-04-30', 'valor': 51.02},
 {'fecha': '2024-04-29', 'valor': 50.47},
 {'fecha': '2024-04-26', 'valor': 50.08},
 {'fecha': '2024-04-25', 'valor': 57.16},
 {'fecha': '2024-04-24', 'valor': 60.09},
 {'fecha': '2024-04-23', 'valor': 60.66},
 {'fecha': '2024-04-22', 'valor': 60.48},
 {'fecha': '2024-04-19', 'valor': 60.17},
 {'fecha': '2024-04-18', 'valor': 60.81},
 {'fecha': '2024-04-17', 'valor': 60.24},
 {'fecha': '2024-04-16', 'valor': 60.76},
 {'fecha': '2024-04-15', 'valor': 59.26},
 {'fecha': '2024-04-12', 'valor': 60.85},
 {'fecha': '2024-04-11', 'valor': 66.25},
 {'fecha': '2024-04-10', 'valor': 67.92},
 {'fecha': '2024-04-09', 'valor': 68.98},

In [7]:
df_hist = pd.DataFrame(data_monetaria["results"][0]["detalle"]) 
print(df_hist.head())

        fecha  valor
0  2026-03-27  23.90
1  2026-03-26  25.10
2  2026-03-25  24.88
3  2026-03-20  24.97
4  2026-03-19  25.95

## Tasas por banco

El BCRA tiene un comparador público de tasas de plazos fijos, 
pero no tiene API documentada. Al inspeccionar el tráfico de red se puede 
acceder directamente al endpoint que alimenta la página.

In [8]:
url_bancos = "https://www.bcra.gob.ar/api-plazos-fijos.php"

response_bancos = requests.get(url_bancos, timeout=10)
response_bancos.raise_for_status()
data_bancos = response_bancos.json()

print(data_bancos.keys())

dict_keys(['success', 'top10', 'otros'])

In [9]:
df_top10 = pd.DataFrame(data_bancos["top10"])
df_otros = pd.DataFrame(data_bancos["otros"])
df_bancos = pd.concat([df_top10, df_otros], ignore_index=True) 

df_bancos.head()

,codigo,entidad,logo_url,tasa_con_relacion,tasa_sin_relacion,web
0,11,BANCO DE LA NACION ARGENTINA ...,http://www.bcra.gob.ar/archivos/Imagenes/logos...,22.0,0.0,
1,72,BANCO SANTANDER ARGENTINA S.A. ...,http://www.bcra.gob.ar/archivos/Imagenes/logos...,20.0,0.0,
2,7,BANCO DE GALICIA Y BUENOS AIRES S.A. ...,http://www.bcra.gob.ar/archivos/Imagenes/logos...,21.0,0.0,
3,14,BANCO DE LA PROVINCIA DE BUENOS AIRES ...,http://www.bcra.gob.ar/archivos/Imagenes/logos...,23.0,0.0,
4,17,BANCO BBVA ARGENTINA S.A. ...,http://www.bcra.gob.ar/archivos/Imagenes/logos...,21.0,0.0,

## Fecha de los datos

La API utilizada para obtener las tasas de plazo fijo por banco no incluye
un campo de "fecha".

Por esta razón se agrega una columna `fecha` que representa la fecha de
extracción de los datos.

Las tasas obtenidas corresponden a las tasas vigentes al momento de
consultar la API.

In [10]:
df_bancos = df_bancos[["codigo","entidad","tasa_con_relacion"]]

df_bancos = df_bancos.rename(columns={
    "entidad":"banco",
    "tasa_con_relacion":"tasa_pf_30d"
})

fecha_hoy = date.today() 
df_bancos["fecha"] = fecha_hoy

df_bancos.head()

,codigo,banco,tasa_pf_30d,fecha
0,11,BANCO DE LA NACION ARGENTINA ...,22.0,2026-03-31
1,72,BANCO SANTANDER ARGENTINA S.A. ...,20.0,2026-03-31
2,7,BANCO DE GALICIA Y BUENOS AIRES S.A. ...,21.0,2026-03-31
3,14,BANCO DE LA PROVINCIA DE BUENOS AIRES ...,23.0,2026-03-31
4,17,BANCO BBVA ARGENTINA S.A. ...,21.0,2026-03-31

## Spread

El *spread* se define como la diferencia entre la tasa de plazo fijo ofrecida por cada banco y el promedio ponderado del sistema financiero publicado por el BCRA.

La comparación se realiza entre las tasas vigentes y el promedio del mercado del día anterior.

In [11]:
data_monetaria.keys()

dict_keys(['status', 'metadata', 'results'])

In [12]:
valor_promedio = data_monetaria["results"][0]["detalle"][0]["valor"]

df_bancos["promedio_bcra"] = valor_promedio 
df_bancos["spread"] = df_bancos["tasa_pf_30d"] - df_bancos["promedio_bcra"]

df_bancos.head()

,codigo,banco,tasa_pf_30d,fecha,promedio_bcra,spread
0,11,BANCO DE LA NACION ARGENTINA ...,22.0,2026-03-31,23.9,-1.9
1,72,BANCO SANTANDER ARGENTINA S.A. ...,20.0,2026-03-31,23.9,-3.9
2,7,BANCO DE GALICIA Y BUENOS AIRES S.A. ...,21.0,2026-03-31,23.9,-2.9
3,14,BANCO DE LA PROVINCIA DE BUENOS AIRES ...,23.0,2026-03-31,23.9,-0.9
4,17,BANCO BBVA ARGENTINA S.A. ...,21.0,2026-03-31,23.9,-2.9

In [13]:
df_bancos['banco'] = df_bancos['banco'].str.strip().str.upper()

conn = sqlite3.connect("../tasas_bancos.db") 
 
tabla_existe = conn.execute("""
    SELECT name FROM sqlite_master 
    WHERE type='table' AND name='tasas_bancos'
""").fetchone()

if tabla_existe:
    conn.execute("DELETE FROM tasas_bancos WHERE fecha = ?", (fecha_hoy.isoformat(),))
    conn.commit()

df_bancos.to_sql(
    "tasas_bancos",
    conn,
    if_exists="append",
    index=False
)

conn.commit()
conn.close()